const mensajes = {
  feliz: [
    "¡supongo que sera un dia hermoso!",
    "Sigue sonriendo, tu alegria es contagiosa",
    "demonios...hoy sacaras los colmillitos hermosos",
    "arrasa con todo no queda de otra",
    "mereces esto y mucho mas...umm se",
    "esos ojos y la sonrisa...nos vas a deslumbrar",
    "solo no te olvides de otras cosas ok...",
    "bueno...que te pico. porque hare que lo sientas diario",
    "estar cerca de ti se sentira calido hoy",
    "tu sonrisa deberia ser patrimonio de la humanidad",
    "el que vaya a quitarte esa sonrisa...se muere",
    "haces que el dia...se sienta mejor",
    "hicieron contigo la mejor obra de arte...eres tan hermosa",
    "lo lograras...creeme ya estas empezando con buena actitud",
    "verte feliz es la cosa favorita de mi mundo y el de todos",
    "si estas feliz todo deberia estar bien",
    "...es sonrisa genuina o es ataque de cafeina?",
    "tu felicidad es el mayor logro...y todos lo veran",
    "y bien...todo fue es felicidad y tendras una buena play list para este momento",
    "tu...me sorprendes carol hasta tus risas exageradas...son hermosas",
    "una sonrisa y un buen outfit...y ya esta, eres modelo la mas encantadora y curiosa",
  ],
  triste: [
    "Está bien sentirse así, no estás sola.",
    "Llora si lo necesitas, es parte de sanar.",
    "Mañana será mejor, te lo prometo.",
    "esta bien, solo no lo ocultes importas..y mucho",
    "la vida es una montaña rusa...solo espera la subida",
    "siempre hay alguien escuchando recuerda...necesitas ser escuchada",
    "no dejare...que estes asi, solo no lo guardes",
    "Tú mereces todo lo bueno, incluso cuando no lo sientas.",
    "Incluso en tus días grises, sigues iluminando el mundo..no lo olvides",
    "Tienes una luz muy bonita, incluso cuando crees que está apagada",
    "A veces necesitas una pausa, no porque seas débil, sino porque has sido fuerte por mucho tiempo",
    "Siempre he admirado tu forma de ser, incluso en tus momentos más callados.",
    " eres una persona valiosa en cada momento",
    "se de lo que eres capaz...asi que no tengas miedo a este momento, lo pasaras",
    "oye te di algo para que te protega no te pasara nada malo, te lo prometo",
    "carol recuerda eres la mejor luz del mundo, no lo olvides nada ni nadie podra apagarte",
    "yo también he llorado por cosas feas… como ver mi cuenta bancaria",
    "La vida a veces apesta, pero al menos tú no...te amo",
    "hasta los mas grandes lloran...tu porque no deberias?",
    "si tienes miedo al que diran o como te critiquen...carol son tus descisiones y llegaras lejos",
    "deberias saber que no esta mal sentirse asi...lo malo es que intentes hacer como si no pasara",
    "eres hermosa..no ocultes ni dejes que otros jodan esa hermosa sonrisa",
    "no queda de otra...quienes son matemos al enemigo",
  ],
  molesta: [
    "Respira hondo, y piensa...despues putea",
    "amor...si necesitas golpear algo...tengo un peluche",
    "Expresa lo que sientes, si la violencia es necesaria....pos no queda de otra",
    "hagamos la lista...y despues quemalo...la hoja..guarda para recordar",
    "no merecen que le mandes tus tik toks",
    "una cosa...se puede golpear?",
    "alejate de los cutters porfa",
    "haber yo te dije...putealos",
    "llama y dime la lista de enemigos...por cada uno un dulce",
    "te ayudare...a cargar los cuerpos",
    "hagas lo que hagas...igual lo haras pa que te digo",
    "ya sabes...defrente al cuello...pero corre..a verda no puedes",
    "sabes...tienes linda mirada cuando te enojas...algo...no me mates",
    "solo no rompas nada...no golpees la laptop o el celular",
    "respira..piensa..reflexiona..ya despues golpeas",
    "tenemos que ver el lado positivo...de no matar",
    "carol...entre golosinas y cafe...que deseas para calmar la ira",
    "siempre hay gente mierda...pero no es necesario pisarlo pasa de ellos",
    "vamos se que esto es momentario...pero dilo putea..dios mio",
    "eres...increible pero no quiero que te guardes el enojo...no me molestare",
    "u nivel de furia está en modo jefa final. Me encantaría ser tu secuaz en esta misión de venganza",
    "¿Quieres que vayamos a mirar gente fea y criticar sus decisiones de peinado hasta que se te pase?",
    "¿Golpeamos una almohada juntos?",
    "Mereces que te escuchen y te respeten, incluso cuando estás enojada",
    "yo no me ire ni molestare...si vienes molesta...asi que tranqui y diloo",
    "dios...y pensaba que la madre naturaleza era dura",
  ],
  aburrida: [
    "¿Qué tal probar algo nuevo hoy?",
    "A veces el aburrimiento es creatividad esperando salir.",
    "Haz una locura divertida, aunque sea pequeña.",
    "Te apuesto que no puedes dibujar un gato con los ojos cerrados.",
    "¿Quieres que inventemos una historia absurda ?",
    "Podemos aburrirnos juntos, pero con estilo. ¿Te parece?",
    "Tu aburrimiento me da excusa perfecta para robar tu atención.",
    "Si estás aburrida, es porque el mundo no está a tu altura hoy.",
    "Tratar de lamerte el codo. pero si puedes...te invito lo que quieras",
    "Levantar solo una ceja...se podra despues de 10 minutos",
    "Los flamencos no nacen rosados. se ponen asi por lo que comen...y tu que comes para estar bonita",
    "Tu pie es aproximadamente del mismo largo que tu antebrazo. eso ni lo sabia",
    "sabias que nosotros brillamos pero es tan bajo el brillo que no lo vemos...pero si te veo a ti",
    "Tu estómago tiene acido que puede disolver una hoja de afeitar. pero como tienes gastritis...creo que eso y mas",
    "las hormigas no duermen,descansan...pero tu no eres hormiga asi que ni se te ocurra",
    "las vacas tienen mejores amigas...no se como bromear con eso...pero eres linda(no te dije vaca)",
    "las abejas pueden reconocer rostros asi que no le robes su miel",
    "cuando parpadeas tus ojos hacen pausa visual",
    "hay una fobia llamada cafefobia...cosa que se que no tienes",
    "la persona mas enana...aun esta viva...y la mas hermosa esta leyendo esto",
    "existe una teoria llamada las voces de tu cabeza son otra persona...da miedo",
    "existe..una creencia de las llamas gemelas..tengo cierta creencia cuando estoy contigo...y da miedo",
    "ahora quieres saber la ley que dice que lo que pienses atraeras...y existe esa posibilidad",
    "existe un tesoro que nunca se podra encontrar no porque sea falso...si no porque no saben ni de donde es",
    "....sabes algunos piensan que saben como pienso y hasta ahora nadie sabe lo que hare ni pensare...crees poder descifrarme?",

  ]
};

function mostrarMensaje(emocion) {
  const lista = mensajes[emocion];
  const mensajeAleatorio = lista[Math.floor(Math.random() * lista.length)];
  document.getElementById("mensaje").textContent = mensajeAleatorio;
}
